{
 "title": "MiniSub Telemetry",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Power Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Thruster 0 VIN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_voltage{topic=\"power_thruster_0\"}"
    }
   ]
  },
  {
   "title": "Thruster 1 VIN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_voltage{topic=\"power_thruster_1\"}"
    }
   ]
  },
  {
   "title": "Thruster 0 CUR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_current{topic=\"power_thruster_0\"}"
    }
   ]
  },
  {
   "title": "Thruster 1 CUR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_current{topic=\"power_thruster_1\"}"
    }
   ]
  },
  { "title": "IMU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Orientation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "imu_orientation", "legendFormat": "{{axis}}" }
   ]
  },
  {
   "title": "Angular Velecity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "targets": [
    { "expr": "imu_angular_velocity", "legendFormat": "{{axis}}" }
   ]
  },
  {
   "title": "Linear Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "imu_linear_acceleration", "legendFormat": "{{axis}}" }
   ]
  }
 ]
}